#!/usr/bin/env python3
"""Combine the numbered Calyx documentation files into a single master .md.

Scans this script's own directory for documentation files named `NN_*.md`
(two leading digits), sorts them numerically, and concatenates them — in the
order 00, 01, 02, ... 24 — into one output file.

Helper/scaffolding files (`_SPEC.md`, `_open_issues.json`) and the output file
itself are intentionally excluded so the script is safe to re-run.

Usage:
    python combine_docs.py
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT_NAME = "CALYX_COMPLETE_DOCUMENTATION.md"
# Matches "00_index.md", "01_system_overview.md", ... but NOT "_SPEC.md".
DOC_PATTERN = re.compile(r"^(\d{2})_.*\.md$")


def find_docs(directory: Path):
    """Return (number, Path) for every NN_*.md doc, sorted by number then name."""
    docs = []
    for path in directory.iterdir():
        if not path.is_file():
            continue
        if path.name == OUTPUT_NAME:
            continue
        m = DOC_PATTERN.match(path.name)
        if m:
            docs.append((int(m.group(1)), path))
    docs.sort(key=lambda t: (t[0], t[1].name))
    return docs


def combine(docs, out_path: Path):
    parts = []
    parts.append("# Calyx — Complete Technical Documentation (Combined)\n")
    parts.append(
        "_This file is auto-generated by `combine_docs.py` — it concatenates the "
        "numbered documentation series in order. Cross-reference links of the form "
        "`[NN_name.md](NN_name.md)` point to the standalone files in the same folder._\n"
    )
    parts.append("\n## Combined contents\n")
    for number, path in docs:
        parts.append(f"- `{path.name}`")
    parts.append("\n")

    for number, path in docs:
        text = path.read_text(encoding="utf-8")
        parts.append("\n\n")
        parts.append(f"<!-- ===== BEGIN {path.name} ===== -->\n")
        parts.append("\n---\n\n")
        parts.append(text.rstrip())
        parts.append("\n")
        parts.append(f"\n<!-- ===== END {path.name} ===== -->\n")

    out_path.write_text("".join(parts), encoding="utf-8")


def main():
    docs = find_docs(HERE)
    if not docs:
        print("No NN_*.md documentation files found next to this script.", file=sys.stderr)
        return 1

    out_path = HERE / OUTPUT_NAME
    combine(docs, out_path)

    total_bytes = out_path.stat().st_size
    print(f"Combined {len(docs)} documents into {out_path.name}")
    for number, path in docs:
        print(f"  {number:02d}  {path.name}")
    print(f"Output: {out_path}  ({total_bytes:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
