#!/usr/bin/env bash
# ============================================================================
#  aiwonder-build-setup.sh — idempotent provisioning of build acceleration
#  that is MACHINE-SPECIFIC and therefore must NOT live in the committed,
#  portable repo config (.cargo/config.toml stays machine-agnostic so it can't
#  break Windows/local authoring checkouts; see docs/implementation/02_BUILD_PERFORMANCE.md).
# ----------------------------------------------------------------------------
#  What it sets up on the build host (no sudo required — all userspace):
#    1. A machine-local Cargo config one level ABOVE the repo, inside CALYX_HOME,
#       which cargo auto-discovers for every Calyx build (repo/ and any worktree
#       are children of CALYX_HOME) without affecting other projects on the box:
#         - link with mold (multi-threaded; saturates all cores at link time)
#         - disable incremental compilation (its cache grew to ~61 GB on this
#           shared, high-churn host and gives little benefit here)
#    2. cargo-sweep (bounded target-dir GC tool)
#    3. a daily user cron that runs scripts/target-gc.sh to cap the canonical
#       main checkout's opt-in target/ size
#
#  Safe to re-run. Fail-loud: missing prerequisites abort with a clear message.
# ============================================================================
set -euo pipefail

if [[ -f "$HOME/.cargo/env" ]]; then
  source "$HOME/.cargo/env"
fi

CALYX_HOME="${CALYX_HOME:-/home/croyse/calyx}"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: required tool not found on PATH: $1" >&2
    exit 1
  }
}
require mold
require clang
require cargo
require crontab

# 1) Machine-local cargo config (mold linker + no incremental + aiwonder
#    CUDA/cuVS runtime search paths for standalone release binaries).
mkdir -p "$CALYX_HOME/.cargo"
cat > "$CALYX_HOME/.cargo/config.toml" <<'EOF'
# ============================================================================
#  Machine-local Cargo config for this build host — NOT in git.
#  Generated by repo/scripts/aiwonder-build-setup.sh; edit there, not here.
#  Lives above repo/ inside CALYX_HOME so cargo auto-discovers it for every
#  Calyx build without touching other projects on this host and without ever
#  being seen by Windows/local authoring checkouts (which never have this parent dir).
# ============================================================================
[build]
# High-churn shared host: incremental's cache (~61 GB observed) is not worth the
# disk; line-tables-only debuginfo already keeps rebuilds fast.
incremental = false

[env]
# Keep CUDA autodiscovery rooted at the real CUDA 13.3 toolkit. Some Rust and
# CMake CUDA builders derive include/lib paths from the literal nvcc path
# returned by PATH lookup; /usr/local/bin/nvcc is a symlink whose parent would
# incorrectly resolve to /usr/local/include.
CUDA_HOME = { value = "/usr/local/cuda-13.3", force = true }
CUDA_PATH = { value = "/usr/local/cuda-13.3", force = true }
CUDA_ROOT = { value = "/usr/local/cuda-13.3", force = true }
CUDAToolkit_ROOT = { value = "/usr/local/cuda-13.3", force = true }
NVCC = { value = "/usr/local/cuda-13.3/bin/nvcc", force = true }

# cuvs-sys 26.6 needs the CMake package dirs for cuVS and its RAPIDS
# dependencies plus the runtime shared-library dirs. These packages live in the
# aiwonder Python 3.14 venv under CALYX_HOME and are not portable repo config.
CMAKE_PREFIX_PATH = { value = "/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libcuvs/lib64/cmake/cuvs:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libraft/lib64/cmake/raft:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/librmm/lib64/cmake/rmm:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/rapids_logger/lib64/cmake/rapids_logger", force = true }
LD_LIBRARY_PATH = { value = "/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libcuvs/lib64:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libraft/lib64:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/librmm/lib64:/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/rapids_logger/lib64:/usr/local/cuda-13.3/targets/x86_64-linux/lib", force = true }

[target.x86_64-unknown-linux-gnu]
# mold is multi-threaded and links several-fold faster than the default
# rust-lld, using all cores. clang is the link driver that invokes it.
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
  # RAPIDS wheels carry transitive shared-library dependencies (cuVS -> RMM ->
  # rapids_logger). Linux RUNPATH is not applied recursively for those
  # transitive loads, so aiwonder release binaries need old-style RPATH.
  "-C", "link-arg=-Wl,--disable-new-dtags",
  "-C", "link-arg=-Wl,-rpath,/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libcuvs/lib64",
  "-C", "link-arg=-Wl,-rpath,/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/libraft/lib64",
  "-C", "link-arg=-Wl,-rpath,/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/librmm/lib64",
  "-C", "link-arg=-Wl,-rpath,/home/croyse/calyx/venvs/cuvs-cu13-26.6/lib/python3.14/site-packages/rapids_logger/lib64",
  "-C", "link-arg=-Wl,-rpath,/usr/local/cuda-13.3/targets/x86_64-linux/lib",
]
EOF
echo "[setup] wrote $CALYX_HOME/.cargo/config.toml"

# 2) cargo-sweep for bounded target-dir GC.
if ! command -v cargo-sweep >/dev/null 2>&1; then
  echo "[setup] installing cargo-sweep ..."
  cargo install cargo-sweep
fi
echo "[setup] cargo-sweep: $(command -v cargo-sweep) ($(cargo-sweep --version 2>/dev/null || echo '?'))"

# 2b) cargo-nextest: parallel test runner used by scripts/check.sh.
if ! command -v cargo-nextest >/dev/null 2>&1; then
  echo "[setup] installing cargo-nextest ..."
  cargo install cargo-nextest --locked
fi
echo "[setup] cargo-nextest: $(command -v cargo-nextest) ($(cargo-nextest --version 2>/dev/null || echo '?'))"

# 3) Daily user cron to bound the canonical checkout's opt-in shared target dir.
#    Always reference the canonical checkout ($CALYX_HOME/repo), never $repo_root:
#    this script may be run from an ephemeral worktree, but the cron must survive
#    that worktree being removed.
mkdir -p "$CALYX_HOME/logs"
gc_script="$CALYX_HOME/repo/scripts/target-gc.sh"
cron_line="0 4 * * * CARGO_TARGET_DIR=$CALYX_HOME/target CALYX_TARGET_MAXSIZE=\${CALYX_TARGET_MAXSIZE:-40GB} bash $gc_script >> $CALYX_HOME/logs/target-gc.log 2>&1"
# Replace any previous target-gc entry, keep everything else.
( crontab -l 2>/dev/null | grep -v 'target-gc.sh' || true; echo "$cron_line" ) | crontab -
echo "[setup] GC script: $gc_script"
echo "[setup] installed daily target-gc cron (04:00 UTC):"
crontab -l | grep 'target-gc.sh'

echo "[setup] done. Verify a build produces the expected binary:"
echo "        cd $CALYX_HOME/repo && scripts/build-verified-calyx.sh --require-string calyx"

# ----------------------------------------------------------------------------
#  4. Install the repo pre-push hook (cargo fmt --check gate). Version-controlled
#     in .githooks/; core.hooksPath is per-clone local config, so wire it here.
#     Idempotent. Prevents the fmt-dirty-merge class of breakage that bit
#     PRs #530/#517/#475/#453 when the manual gate was skipped.
# ----------------------------------------------------------------------------
git -C "$repo_root" config core.hooksPath .githooks
echo "setup: core.hooksPath set to .githooks (pre-push fmt gate active)"
